[project]
name = "kdag-dataforge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Koustav Manna", email = "koustaviitjee@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
kdag-dataforge = "kdag_dataforge:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
